export const USER_SESSION_LOG_REGISTERED_SUCCESSFULLY = "USER_SESSION_LOG_REGISTERED_SUCCESSFULLY";
export const ERROR_REGISTERING_USER_SESSION_LOG = "ERROR_REGISTERING_USER_SESSION_LOG";
export const USER_SESSION_LOG_FETCH_SUCCESSFULLY = "USER_SESSION_LOG_FETCH_SUCCESSFULLY";
export const USER_SESSION_LOG_FETCH_ERROR = "USER_SESSION_LOG_FETCH_ERROR";
export const USER_SESSION_LOG_EMPTY_FETCH = "USER_SESSION_LOG_EMPTY_FETCH";