export const COMPANY_USER_SUCCESSFULLY_REGISTERED = 'COMPANY_USER_SUCCESSFULLY_REGISTERED';
export const REGISTERING_COMPANY_USER_FAILED = 'REGISTERING_COMPANY_USER_FAILED';


export const REGISTERED_COMPANY_USER_FETCHED_SUCCESSFULLY = 'REGISTERED_COMPANY_USER_FETCHED_SUCCESSFULLY';
export const REGISTERED_COMPANY_USER_EMPTY_RESULTS = 'REGISTERED_COMPANY_USER_EMPTY_RESULTS';
export const ERROR_FETCHING_COMPANY_USER = 'ERROR_FETCHING_COMPANY_USER';



