export const SIGN_UP_SUCCESSFUL = 'SIGN_UP_SUCCESSFUL';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';


export const REGISTERED_ADMINISTRATOR_FETCHED_SUCCESSFULLY = 'REGISTERED_ADMINISTRATOR_FETCHED_SUCCESSFULLY';
export const REGISTERED_ADMINISTRATOR_EMPTY_RESULTS = 'REGISTERED_ADMINISTRATOR_EMPTY_RESULTS';
export const ERROR_FETCHING_ADMINISTRATOR = 'ERROR_FETCHING_ADMINISTRATOR';



