export const SESSION_LOG_REGISTERED_SUCCESSFULLY = "SESSION_LOG_REGISTERED_SUCCESSFULLY";
export const ERROR_REGISTERING_SESSION_LOG = "ERROR_REGISTERING_SESSION_LOG";
export const SESSION_LOG_FETCH_SUCCESSFULLY = "SESSION_LOG_FETCH_SUCCESSFULLY";
export const SESSION_LOG_FETCH_ERROR = "SESSION_LOG_FETCH_ERROR";
export const SESSION_LOG_EMPTY_FETCH = "SESSION_LOG_EMPTY_FETCH";