export const SIGN_UP_SUCCESSFUL = 'SIGN_UP_SUCCESSFUL';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';


export const REGISTERED_ADMIN_FETCHED_SUCCESSFULLY = 'REGISTERED_COMPANY_FETCHED_SUCCESSFULLY';
export const REGISTERED_ADMIN_EMPTY_RESULTS = 'REGISTERED_ADMIN_EMPTY_RESULTS';
export const ERROR_FETCHING_ADMIN = 'ERROR_FETCHING_ADMIN';



