export const OBJECTIVES_SUCCESSFULLY_REGISTERED = 'OBJECTIVES_SUCCESSFULLY_REGISTERED';
export const REGISTERING_OBJECTIVES_FAILED = 'REGISTERING_OBJECTIVES_FAILED';


export const REGISTERED_OBJECTIVES_FETCHED_SUCCESSFULLY = 'REGISTERED_OBJECTIVES_FETCHED_SUCCESSFULLY';
export const REGISTERED_OBJECTIVES_EMPTY_RESULTS = 'REGISTERED_OBJECTIVES_EMPTY_RESULTS';
export const ERROR_FETCHING_OBJECTIVES = 'ERROR_FETCHING_OBJECTIVES';
export const SET_PERCENTAGE = 'SET_PERCENTAGE';
export const SET_OBJECTIVE = 'SET_OBJECTIVE';

export const PROJECTS_AND_OBJECTIVES_SUCCESSFULLY_FETCHED = 'PROJECTS_AND_OBJECTIVES_SUCCESSFULLY_FETCHED';
export const PROJECTS_AND_OBJECTIVES_FETCH_FAILED = 'PROJECTS_AND_OBJECTIVES_FETCH_FAILED';




