export const GENDER_SUCCESSFULLY_REGISTERED = 'GENDER_SUCCESSFULLY_REGISTERED';
export const REGISTERING_GENDER_FAILED = 'REGISTERING_GENDER_FAILED';


export const REGISTERED_GENDER_FETCHED_SUCCESSFULLY = 'REGISTERED_GENDER_FETCHED_SUCCESSFULLY';
export const REGISTERED_GENDER_EMPTY_RESULTS = 'REGISTERED_GENDER_EMPTY_RESULTS';
export const ERROR_FETCHING_GENDER = 'ERROR_FETCHING_GENDER';



