export const PROJECTS_SUCCESSFULLY_REGISTERED = 'PROJECTS_SUCCESSFULLY_REGISTERED';
export const REGISTERING_PROJECTS_FAILED = 'REGISTERING_PROJECTS_FAILED';


export const REGISTERED_PROJECTS_FETCHED_SUCCESSFULLY = 'REGISTERED_PROJECTS_FETCHED_SUCCESSFULLY';
export const REGISTERED_PROJECTS_EMPTY_RESULTS = 'REGISTERED_PROJECTS_EMPTY_RESULTS';
export const ERROR_FETCHING_PROJECTS = 'ERROR_FETCHING_PROJECTS';


export const BEGIN_PROJECT_SELECTION = 'BEGIN_PROJECT_SELECTION';
export const STORE_PROJECT = 'STORE_PROJECT';
export const PROJECT_SELECTION_SUCCESS = 'PROJECT_SELECTION_SUCCESS';
export const WRONG_SELECTION = 'WRONG_SELECTION';
export const AN_ERROR_OCCURED_DURING_SELECTION = 'AN_ERROR_OCCURED_DURING_SELECTION';
export const SET_PROJECT="SET_PROJECT";

export const PROJECT_PROGRESS_SUCCESSFULLY_UPDATED = 'PROJECT_PROGRESS_SUCCESSFULLY_UPDATED';
export const PROJECT_PROGRESS_UPDATE_FAILED="PROJECT_PROGRESS_UPDATE_FAILED";



