export const PROJECTS_SUCCESSFULLY_REGISTERED = 'PROJECTS_SUCCESSFULLY_REGISTERED';
export const REGISTERING_PROJECTS_FAILED = 'REGISTERING_PROJECTS_FAILED';


export const REGISTERED_PROJECTS_FETCHED_SUCCESSFULLY = 'REGISTERED_PROJECTS_FETCHED_SUCCESSFULLY';
export const REGISTERED_PROJECTS_EMPTY_RESULTS = 'REGISTERED_PROJECTS_EMPTY_RESULTS';
export const ERROR_FETCHING_PROJECTS = 'ERROR_FETCHING_PROJECTS';



