// fetching all users
export const USERS_FETCHED_SUCCESSFULLY = "USERS_FETCHED_SUCCESSFULLY";



// fetch all acess privileges
export const USERS_ACCESS_FETCHED_SUCCESSFULLY = "USERS_ACCESS_FETCHED_SUCCESSFULLY";
export const USERS_ACCESS_FETCH_FAILED = "USERS_ACCESS_FETCH_FAILED";
export const USERS_ACCESS_FETCH_EMPTY_RESULT = "USERS_ACCESS_FETCH_EMPTY_RESULT";
export const PRIVILEGES_SUCCESSFULLY_UPDATED = "PRIVILEGES_SUCCESSFULLY_UPDATED";
export const PRIVILEGES_UPDATE_RESET = "PRIVILEGES_UPDATE_RESET";
export const PERMISSION_UPDATE_FAILED = "PERMISSION_UPDATE_FAILED";



