export const PRIVILEGES_SUCCESSFULLY_UPDATED = 'PRIVILEGES_SUCCESSFULLY_UPDATED';
export const PRIVILEGES_UPDATE_RESET = 'PRIVILEGES_UPDATE_RESET';
export const UPDATED_PRIVILEGES_FAILED = 'UPDATED_PRIVILEGES_FAILED';


export const REGISTERED_PRIVILEGES_FETCHED_SUCCESSFULLY = 'REGISTERED_PRIVILEGES_FETCHED_SUCCESSFULLY';
export const REGISTERED_PRIVILEGES_EMPTY_RESULTS = 'REGISTERED_PRIVILEGES_EMPTY_RESULTS';
export const ERROR_FETCHING_PRIVILEGES = 'ERROR_FETCHING_PRIVILEGES';



