// fetching all users
export const USERS_FETCHED_SUCCESSFULLY = "USERS_FETCHED_SUCCESSFULLY";
export const USERS_FETCH_FAILED = "USERS_FETCH_FAILED";
export const USERS_FETCH_EMPTY_RESULT = "USERS_FETCH_EMPTY_RESULT";

// fetch all user roles
export const USERS_ROLES_FETCHED_SUCCESSFULLY = "USERS_ROLES_FETCHED_SUCCESSFULLY";
export const USERS_ROLES_FETCH_FAILED = "USERS_ROLES_FETCH_FAILED";
export const USERS_ROLES_FETCH_EMPTY_RESULT = "USERS_ROLES_FETCH_EMPTY_RESULT";

// fetch all acess privileges
export const USERS_ACCESS_FETCHED_SUCCESSFULLY = "USERS_ACCESS_FETCHED_SUCCESSFULLY";
export const USERS_ACCESS_FETCH_FAILED = "USERS_ACCESS_FETCH_FAILED";
export const USERS_ACCESS_FETCH_EMPTY_RESULT = "USERS_ACCESS_FETCH_EMPTY_RESULT";
export const PRIVILEGES_SUCCESSFULLY_UPDATED = "PRIVILEGES_SUCCESSFULLY_UPDATED";
export const UPDATED_PRIVILEGES_FAILED = "UPDATED_PRIVILEGES_FAILED";
export const PRIVILEGES_UPDATE_RESET = "PRIVILEGES_UPDATE_RESET";
export const PERMISSION_UPDATE_FAILED = "PERMISSION_UPDATE_FAILED";



