
// fetch all access privileges
export const ADMIN_ACCESS_FETCHED_SUCCESSFULLY = "ADMIN_ACCESS_FETCHED_SUCCESSFULLY";
export const ADMIN_ACCESS_FETCH_FAILED = "ADMIN_ACCESS_FETCH_FAILED";
export const ADMIN_ACCESS_FETCH_EMPTY_RESULT = "ADMIN_ACCESS_FETCH_EMPTY_RESULT";
export const PRIVILEGES_SUCCESSFULLY_UPDATED = "PRIVILEGES_SUCCESSFULLY_UPDATED";
export const PRIVILEGES_UPDATE_RESET = "PRIVILEGES_UPDATE_RESET";
export const PERMISSION_UPDATE_FAILED = "PERMISSION_UPDATE_FAILED";



