export const TEAM_MEMBER_SUCCESSFULLY_REGISTERED = 'TEAM_MEMBER_SUCCESSFULLY_REGISTERED';
export const REGISTERING_TEAM_MEMBER_FAILED = 'REGISTERING_TEAM_MEMBER_FAILED';


export const REGISTERED_TEAM_MEMBER_FETCHED_SUCCESSFULLY = 'REGISTERED_TEAM_MEMBER_FETCHED_SUCCESSFULLY';
export const REGISTERED_TEAM_MEMBER_EMPTY_RESULTS = 'REGISTERED_TEAM_MEMBER_EMPTY_RESULTS';
export const ERROR_FETCHING_TEAM_MEMBER = 'ERROR_FETCHING_TEAM_MEMBER';



