// fetch all acess BRANCH_PROJECT_STATUS
export const BRANCH_PROJECT_FETCHED_SUCCESSFULLY = "BRANCH_PROJECT_FETCHED_SUCCESSFULLY";
export const BRANCH_PROJECT_FETCH_FAILED = "BRANCH_PROJECT_FETCH_FAILED";
export const BRANCH_PROJECT_FETCH_EMPTY_RESULT = "BRANCH_PROJECT_FETCH_EMPTY_RESULT";
export const BRANCH_PROJECT_STATUS_SUCCESSFULLY_UPDATED = "BRANCH_PROJECT_STATUS_SUCCESSFULLY_UPDATED";
export const BRANCH_PROJECT_STATUS_RESET = "BRANCH_PROJECT_UPDATE_RESET";
export const BRANCH_PROJECT_STATUS_UPDATE_FAILED = "BRANCH_PROJECT_STATUS_UPDATE_FAILED";



