
// fetch all access privileges
export const ADMINISTRATOR_ACCESS_FETCHED_SUCCESSFULLY = "ADMINISTRATOR_ACCESS_FETCHED_SUCCESSFULLY";
export const ADMINISTRATOR_ACCESS_FETCH_FAILED = "ADMINISTRATOR_ACCESS_FETCH_FAILED";
export const ADMINISTRATOR_ACCESS_FETCH_EMPTY_RESULT = "ADMINISTRATOR_ACCESS_FETCH_EMPTY_RESULT";
export const PRIVILEGES_SUCCESSFULLY_UPDATED = "PRIVILEGES_SUCCESSFULLY_UPDATED";
export const PRIVILEGES_UPDATE_RESET = "PRIVILEGES_UPDATE_RESET";
export const PERMISSION_UPDATE_FAILED = "PERMISSION_UPDATE_FAILED";



