export const SIGN_UP_SUCCESSFUL = 'SIGN_UP_SUCCESSFUL';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';


export const REGISTERED_USER_FETCHED_SUCCESSFULLY = 'REGISTERED_USER_FETCHED_SUCCESSFULLY';
export const REGISTERED_USER_EMPTY_RESULTS = 'REGISTERED_USER_EMPTY_RESULTS';
export const ERROR_FETCHING_USER = 'ERROR_FETCHING_USER';
export const SET_USER = 'SET_USER';

export const RECORDS_FETCHED_SUCCESSFULLY = 'RECORDS_FETCHED_SUCCESSFULLY';
export const RECORDS_FETCH_EMPTY_RESULTS = 'RECORDS_FETCH_EMPTY_RESULTS';
export const ERROR_FETCHING_RECORDS = 'ERROR_FETCHING_RECORDS';



