
// fetching all users
export const USERS_FETCHED_SUCCESSFULLY = "USERS_FETCHED_SUCCESSFULLY";
export const USERS_FETCH_FAILED = "USERS_FETCH_FAILED";
export const USERS_FETCH_EMPTY_RESULT = "USERS_FETCH_EMPTY_RESULT";

// fetch all user roles
export const USERS_ROLES_FETCHED_SUCCESSFULLY = "USERS_ROLES_FETCHED_SUCCESSFULLY";
export const USERS_ROLES_FETCH_FAILED = "USERS_ROLES_FETCH_FAILED";
export const USERS_ROLES_FETCH_EMPTY_RESULT = "USERS_ROLES_FETCH_EMPTY_RESULT";

// fetch all acess privileges
export const USERS_ACCESS_FETCHED_SUCCESSFULLY = "USERS_ACCESS_FETCHED_SUCCESSFULLY";
export const USERS_ACCESS_FETCH_FAILED = "USERS_ACCESS_FETCH_FAILED";
export const USERS_ACCESS_FETCH_EMPTY_RESULT = "USERS_ACCESS_FETCH_EMPTY_RESULT";
export const PERMISSION_UPDATE_SUCCESSFULL = "PERMISSION_UPDATE_SUCCESSFULL";
export const PERMISSION_UPDATE_FAILED = "PERMISSION_UPDATE_FAILED";




// user login
export const BEGIN_USER_AUTHENTICATION = "BEGIN_USER_AUTHENTICATION";
export const CHECK_ROLE = "CHECK_ROLE";
export const CHECK_PRIVILEGE = "CHECK_PRIVILEGE";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const WRONG_CREDENTIALS = "WRONG_CREDENTIALS";
export const DENIED_ACCESS = "DENIED_ACCESS";





