export const SYSTEM_ADMIN = "SYSTEM_ADMIN";
export const COMPANY_OWNER = "COMPANY_OWNER";
export const REGULAR_SYSTEM_USER = "REGULAR_SYSTEM_USER";
export const IDLE_TIMEOUT = 1000 * 60;
export const DEBOUNCE = 250;

export const BURSAR = "BURSAR";



export const DISPLAY_USER_REGISTRATION_PAGE = "DISPLAY_USER_REGISTRATION_PAGE";
export const DISPLAY_COMPANY_REGISTRATION_PAGE = "DISPLAY_COMPANY_REGISTRATION_PAGE";
export const DISPLAY_USER_MANAGEMENT_PAGE = "DISPLAY_USER_MANAGEMENT_PAGE";

export const DISPLAY_TEAMS = "DISPLAY_TEAMS";

export const DISPLAY_PROJECTS = "DISPLAY_PROJECTS";



