export const COMPANY_SUCCESSFULLY_REGISTERED = 'COMPANY_SUCCESSFULLY_REGISTERED';
export const REGISTERING_COMPANY_FAILED = 'REGISTERING_COMPANY_FAILED';


export const REGISTERED_COMPANY_FETCHED_SUCCESSFULLY = 'REGISTERED_COMPANY_FETCHED_SUCCESSFULLY';
export const REGISTERED_COMPANY_EMPTY_RESULTS = 'REGISTERED_COMPANY_EMPTY_RESULTS';
export const ERROR_FETCHING_COMPANY = 'ERROR_FETCHING_COMPANY';



