export const TEAMS_SUCCESSFULLY_REGISTERED = 'TEAMS_SUCCESSFULLY_REGISTERED';
export const REGISTERING_TEAMS_FAILED = 'REGISTERING_TEAMS_FAILED';


export const REGISTERED_TEAMS_FETCHED_SUCCESSFULLY = 'REGISTERED_TEAMS_FETCHED_SUCCESSFULLY';
export const REGISTERED_TEAMS_EMPTY_RESULTS = 'REGISTERED_TEAMS_EMPTY_RESULTS';
export const ERROR_FETCHING_TEAMS = 'ERROR_FETCHING_TEAMS';

export const TEAM_LEAD_SUCCESSFULLY_REGISTERED = 'TEAM_LEAD_SUCCESSFULLY_REGISTERED';
export const REGISTERING_TEAM_LEAD_FAILED = 'REGISTERING_TEAM_LEAD_FAILED';

export const TEAM_MEMBER_SUCCESSFULLY_REGISTERED = 'TEAM_MEMBER_SUCCESSFULLY_REGISTERED';
export const REGISTERING_TEAM_MEMBER_FAILED = 'REGISTERING_TEAM_MEMBER_FAILED';

export const TEAM_LEAD_IS_CHECK_BOX_CHECKED_SUCCESSFULLY_UPDATED = 'TEAM_LEAD_IS_CHECK_BOX_CHECKED_SUCCESSFULLY_UPDATED';
export const TEAM_LEAD_IS_CHECK_BOX_CHECKED_UPDATE_FAILED = 'TEAM_LEAD_IS_CHECK_BOX_CHECKED_UPDATE_FAILED';

export const SET_TEAM = 'SET_TEAM';
export const PROJECTS_AND_TEAMS_SUCCESSFULLY_FETCHED = "PROJECTS_AND_TEAMS_SUCCESSFULLY_FETCHED";
export const PROJECTS_AND_TEAMS_FETCH_EMPTY = "PROJECTS_AND_TEAMS_FETCH_EMPTY";

export const TEAM_AND_TEAM_LEAD_SUCCESSFULLY_FETCHED ="TEAM_AND_TEAM_LEAD_SUCCESSFULLY_FETCHED";
export const TEAM_AND_TEAM_LEAD_FETCH_EMPTY ="TEAM_AND_TEAM_LEAD_FETCH_EMPTY";
export const TEAM_AND_TEAM_MEMBER_SUCCESSFULLY_FETCHED ="TEAM_AND_TEAM_MEMBER_SUCCESSFULLY_FETCHED";
export const TEAM_AND_TEAM_MEMBER_FETCH_EMPTY ="TEAM_AND_TEAM_MEMBER_FETCH_EMPTY";

