export const TEAMS_SUCCESSFULLY_REGISTERED = 'TEAMS_SUCCESSFULLY_REGISTERED';
export const REGISTERING_TEAMS_FAILED = 'REGISTERING_TEAMS_FAILED';


export const REGISTERED_TEAMS_FETCHED_SUCCESSFULLY = 'REGISTERED_TEAMS_FETCHED_SUCCESSFULLY';
export const REGISTERED_TEAMS_EMPTY_RESULTS = 'REGISTERED_TEAMS_EMPTY_RESULTS';
export const ERROR_FETCHING_TEAMS = 'ERROR_FETCHING_TEAMS';



